rainfocus:
  api-profile-key: 1hGBArn60dAcDabjKLw7jC7s7uRbwNKY
  base-url: 'https://events.rainfocus.com/api/servicenow/v2'
---
spring:
  redis:
    host: 'busybee.redis.cache.windows.net'
    port: 6379
    password: PRUSsYGZlOtNgj0iSB85mA9hhZtRj7aSMAzCaFTJO48=
---
k22.active-events: knowledge2022,k22lasvegas,k22newyork,k22sydney,k22netherlands
